import React from 'react';
import Header from '../components/TermsPrivacyHeader';

const TermsAndConditions = () => {
  return (
    <div className="ad-waitlist min-h-screen bg-gradient-to-br from-white to-green-50">
      <Header />
      <div className="w-full max-w-4xl mx-auto mt-12 sm:mt-20 p-4 sm:p-6 md:p-8">
        <h1 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold text-blue-950 mb-4">Terms and Conditions</h1>
        
        <div className="space-y-4">
          <section className="bg-white border border-gray-200 rounded-lg p-3 sm:p-5">
            <h2 className="text-lg sm:text-xl text-blue-950 font-bold mb-3">1. Definitions</h2>
            <ul className="space-y-3">
              <li className="flex flex-col sm:flex-row sm:items-center bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                <span className="text-blue-950 font-bold mb-1 sm:mb-0 sm:pr-5">Platform</span>
                <span>Refers to the Yepper website and associated services.</span>
              </li>
              <li className="flex flex-col sm:flex-row sm:items-center bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                <span className="text-blue-950 font-bold mb-1 sm:mb-0 sm:pr-5">Web Owner</span>
                <span>An individual or entity that owns a website and creates spaces for advertisements on the platform.</span>
              </li>
              <li className="flex flex-col sm:flex-row sm:items-center bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                <span className="text-blue-950 font-bold mb-1 sm:mb-0 sm:pr-5">Advertiser</span>
                <span>An individual or entity that uses the platform to publish ads.</span>
              </li>
              <li className="flex flex-col sm:flex-row sm:items-center bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                <span className="text-blue-950 font-bold mb-1 sm:mb-0 sm:pr-5">Content</span>
                <span>Refers to all ad images, videos, or other materials uploaded by Advertisers.</span>
              </li>
            </ul>
          </section>

          <section className="bg-white border border-gray-200 rounded-lg p-3 sm:p-5">
            <h2 className="text-lg sm:text-xl text-blue-950 font-bold mb-3">2. Eligibility</h2>
            <ul className="space-y-3">
              <li className="bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                Users must be 18 years or older and have the legal authority to enter into binding agreements.
              </li>
              <li className="bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                By using Yepper, you confirm that all information provided is accurate and truthful.
              </li>
            </ul>
          </section>

          <section className="bg-white border border-gray-200 rounded-lg p-3 sm:p-5">
            <h2 className="text-lg sm:text-xl text-blue-950 font-bold mb-3">3. Web Owner Responsibilities</h2>
            <ul className="space-y-3">
              <li className="flex flex-col sm:flex-row bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                <span className="text-blue-950 font-bold mb-1 sm:mb-0 sm:pr-5">Website Creation</span>
                <span>Web Owners must provide accurate website details, including the website name, URL, and logo.</span>
              </li>
              <li className="flex flex-col sm:flex-row bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                <span className="text-blue-950 font-bold mb-1 sm:mb-0 sm:pr-5">Category and Space Management</span>
                <span>Web Owners are responsible for setting appropriate prices, user counts, availability, and clear instructions for ad spaces.</span>
              </li>
              <li className="flex flex-col sm:flex-row bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                <span className="text-blue-950 font-bold mb-1 sm:mb-0 sm:pr-5">API Integration</span>
                <span>The script API generated by Yepper must be correctly integrated into their website to ensure ads display as intended.</span>
              </li>
              <li className="flex flex-col sm:flex-row bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                <span className="text-blue-950 font-bold mb-1 sm:mb-0 sm:pr-5">Approval of Ads</span>
                <span>Web Owners are responsible for reviewing and approving or rejecting ad requests in a timely manner.</span>
              </li>
            </ul>
          </section>

          <section className="bg-white border border-gray-200 rounded-lg p-3 sm:p-5">
            <h2 className="text-lg sm:text-xl text-blue-950 font-bold mb-3">4. Advertiser Responsibilities</h2>
            <ul className="space-y-3">
              <li className="flex flex-col sm:flex-row bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                <span className="text-blue-950 font-bold mb-1 sm:mb-0 sm:pr-5">Ad Content</span>
                <span>Advertisers must ensure that uploaded ad images or videos comply with applicable laws and do not contain prohibited content such as hate speech, offensive material, or misleading information.</span>
              </li>
              <li className="flex flex-col sm:flex-row bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                <span className="text-blue-950 font-bold mb-1 sm:mb-0 sm:pr-5">Business Information</span>
                <span>Accurate business details, including the name, website, location, and description, must be provided.</span>
              </li>
              <li className="flex flex-col sm:flex-row bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                <span className="text-blue-950 font-bold mb-1 sm:mb-0 sm:pr-5">Payment</span>
                <span>Advertisers must pay for approved ads promptly to ensure publication.</span>
              </li>
            </ul>
          </section>

          <section className="bg-white border border-gray-200 rounded-lg p-3 sm:p-5">
            <h2 className="text-lg sm:text-xl text-blue-950 font-bold mb-3">5. Payments and Fees</h2>
            <ul className="space-y-3">
              <li className="bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                Payments for ad spaces must be processed through the platform's integrated payment system.
              </li>
              <li className="bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                Yepper charges a service fee on each transaction, which is deducted automatically.
              </li>
            </ul>
          </section>

          <section className="bg-white border border-gray-200 rounded-lg p-3 sm:p-5">
            <h2 className="text-lg sm:text-xl text-blue-950 font-bold mb-3">6. Prohibited Activities</h2>
            <ul className="space-y-3">
              <li className="bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                Misrepresentation of business or website details.
              </li>
              <li className="bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                Uploading harmful or illegal content.
              </li>
              <li className="bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                Sharing or selling access to the platform's API script.
              </li>
              <li className="bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                Attempting to bypass Yepper's payment system or fees.
              </li>
            </ul>
          </section>

          <section className="bg-white border border-gray-200 rounded-lg p-3 sm:p-5">
            <h2 className="text-lg sm:text-xl text-blue-950 font-bold mb-3">7. Limitation of Liability</h2>
            <ul className="space-y-3">
              <li className="bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                Yepper is not responsible for any loss or damage arising from the use of the platform, including but not limited to downtime, misconfigured APIs, or disputes between Web Owners and Advertisers.
              </li>
            </ul>
          </section>

          <section className="bg-white border border-gray-200 rounded-lg p-3 sm:p-5">
            <h2 className="text-lg sm:text-xl text-blue-950 font-bold mb-3">8. Termination of Account</h2>
            <ul className="space-y-3">
              <li className="bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                Yepper reserves the right to terminate accounts that violate these terms without prior notice.
              </li>
            </ul>
          </section>

          <section className="bg-white border border-gray-200 rounded-lg p-3 sm:p-5">
            <h2 className="text-lg sm:text-xl text-blue-950 font-bold mb-3">9. Modifications to Terms</h2>
            <ul className="space-y-3">
              <li className="bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                Yepper may update these terms at any time. Continued use of the platform constitutes acceptance of the revised terms.
              </li>
            </ul>
          </section>

          <section className="bg-white border border-gray-200 rounded-lg p-3 sm:p-5">
            <h2 className="text-lg sm:text-xl text-blue-950 font-bold mb-3">10. Contact Information</h2>
            <ul className="space-y-3">
              <li className="bg-white border border-gray-200 text-gray-600 rounded-lg p-3">
                For any questions or concerns regarding these Terms, please contact us at
              </li>
              <a href="mailto:olympusexperts@gmail.com" className="text-blue-600 font-bold hover:underline block p-3">
                olympusexperts@gmail.com
              </a>
            </ul>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions;